-- ==========================================================================
-- Cyber_Path migration 0014 - quiz seed content
-- Three scenario-first questions per seeded topic (81 rows). Questions test
-- understanding and behavior prediction, not trivia. Answer positions vary.
-- Idempotent: re-running updates rows in place (upsert on slug + position).
-- ==========================================================================

insert into public.quiz_questions (topic_slug, position, kind, question, choices, answer_index, explanation) values
('what-is-cybersecurity', 1, 'scenario',
 'A small business keeps customer records on one laptop with no backups and no access control. The laptop is stolen. Which CIA properties are most directly harmed?',
 '[{"id":"a","text":"Integrity only - nothing was changed"},{"id":"b","text":"Confidentiality and availability"},{"id":"c","text":"Availability only - the data still exists elsewhere"},{"id":"d","text":"Non-repudiation"}]'::jsonb,
 1,
 'Theft exposes stored data (confidentiality) and leaves the business without access to it (availability). Nothing was altered, so integrity is intact.'),
('what-is-cybersecurity', 2, 'mcq',
 'Which statement best describes the difference between a vulnerability and an exploit?',
 '[{"id":"a","text":"A vulnerability is a weakness; an exploit is a technique or code that takes advantage of it"},{"id":"b","text":"They are two names for the same thing"},{"id":"c","text":"A vulnerability only exists after an exploit is published"},{"id":"d","text":"An exploit is a weakness; a vulnerability is the act of attacking"}]'::jsonb,
 0,
 'Vulnerability = the weakness. Exploit = the code or technique that uses that weakness to cause harm.'),
('what-is-cybersecurity', 3, 'scenario',
 'A company layers MFA on logins, weekly backups, and staff phishing awareness. Which principle does this combination best illustrate?',
 '[{"id":"a","text":"Least privilege"},{"id":"b","text":"Incident response"},{"id":"c","text":"Threat modeling"},{"id":"d","text":"Defense in depth - multiple layers so one failure is not fatal"}]'::jsonb,
 3,
 'Each control covers a different failure mode; together no single miss breaks security. That is defense in depth.'),
('security-domains', 1, 'scenario',
 'Ransomware is actively encrypting a file server and the team must isolate hosts and restore from backups. Which security domain owns this work?',
 '[{"id":"a","text":"Cryptography engineering"},{"id":"b","text":"Incident response and security operations"},{"id":"c","text":"Compliance auditing"},{"id":"d","text":"Application development"}]'::jsonb,
 1,
 'Containing an active compromise and recovering from it is the incident response and security operations domain.'),
('security-domains', 2, 'mcq',
 'In the NIST Cybersecurity Framework, which function is about discovering that an event has occurred?',
 '[{"id":"a","text":"Detect"},{"id":"b","text":"Identify"},{"id":"c","text":"Recover"},{"id":"d","text":"Govern"}]'::jsonb,
 0,
 'Detect covers ongoing monitoring to spot events. Identify maps assets and risk, Recover restores, Govern sets strategy.'),
('security-domains', 3, 'scenario',
 'An analyst reviews firewall and DNS logs weekly, hunting unusual outbound traffic before it becomes an incident. This activity is best described as',
 '[{"id":"a","text":"Reactive recovery"},{"id":"b","text":"Physical security"},{"id":"c","text":"Proactive detection and threat monitoring"},{"id":"d","text":"Configuration management"}]'::jsonb,
 2,
 'Looking for indicators before an incident escalates is proactive detection - the heart of threat monitoring.'),
('ethics-and-law', 1, 'scenario',
 'A friend asks you to log into their old account and delete posts, sharing the password with you. Why is using shared credentials still the wrong move?',
 '[{"id":"a","text":"Shared credentials make actions unattributable and typically violate terms of service and access policies - proper account recovery is the right path"},{"id":"b","text":"It is fine as long as the password works"},{"id":"c","text":"It is only a problem if the account gets locked"},{"id":"d","text":"Permission between friends removes every policy concern"}]'::jsonb,
 0,
 'Shared credentials break accountability and usually violate policy. If access is legitimately needed, use the platform account-recovery process.'),
('ethics-and-law', 2, 'tf',
 'Running a vulnerability scan against systems you own, with written authorization and a defined scope, is legitimate security testing.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'Authorization, scope, and documentation are exactly what separate ethical testing from unauthorized access.'),
('ethics-and-law', 3, 'mcq',
 'You stumble on a security flaw in a public website during normal browsing. The responsible first move is to',
 '[{"id":"a","text":"Post a public proof of concept to force a fix"},{"id":"b","text":"Prove impact by opening another user account"},{"id":"c","text":"Report it privately to the owner or their disclosure program and stop there"},{"id":"d","text":"Offer the details to whoever pays most"}]'::jsonb,
 2,
 'Coordinated disclosure: report privately, do not exploit, do not access data that is not yours.'),
('career-overview', 1, 'mcq',
 'Which role-to-work pairing is most accurate?',
 '[{"id":"a","text":"Penetration tester - designs backup strategy"},{"id":"b","text":"SOC analyst - writes frontend code"},{"id":"c","text":"GRC analyst - performs memory forensics daily"},{"id":"d","text":"SOC analyst - triages alerts and investigates incidents; pentester - simulates attacks to find weaknesses"}]'::jsonb,
 3,
 'SOC (blue team) defends and investigates; pentesters (offensive) attack with permission to find and fix weaknesses.'),
('career-overview', 2, 'scenario',
 'A junior wants defensive work built around logs, detections, and incident triage. Which path fits best?',
 '[{"id":"a","text":"Blue team / SOC analyst"},{"id":"b","text":"Red team operations"},{"id":"c","text":"Bug bounty hunting"},{"id":"d","text":"Cloud infrastructure engineering"}]'::jsonb,
 0,
 'Alert triage, log analysis and detections are the daily bread of SOC and blue-team roles.'),
('career-overview', 3, 'tf',
 'Many people enter security through adjacent roles like helpdesk, sysadmin, or networking, because security builds on OS and network fundamentals.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'Deep OS and networking fundamentals are what security work sits on top of - adjacent roles are a proven entry path.'),
('home-lab-safety', 1, 'scenario',
 'You want to practice network scanning legally and safely at home. Which setup is correct?',
 '[{"id":"a","text":"Scan your ISP-assigned public range for interesting hosts"},{"id":"b","text":"Scan a random internet server once, for science"},{"id":"c","text":"An isolated virtual lab network (host-only or internal) with VMs you own, and scans limited to that network"},{"id":"d","text":"Scan your employer network without asking, for learning"}]'::jsonb,
 2,
 'Only ever test systems you own or are explicitly authorized to test. An isolated virtual lab keeps it legal and contained.'),
('home-lab-safety', 2, 'mcq',
 'Why snapshot a lab VM before experimenting with it?',
 '[{"id":"a","text":"Snapshots make the VM run faster"},{"id":"b","text":"To roll back to a known-good state after an experiment breaks it"},{"id":"c","text":"To encrypt the virtual disk"},{"id":"d","text":"To hide the VM from the host operating system"}]'::jsonb,
 1,
 'Snapshots are the undo button of lab work: break it, learn, revert, repeat.'),
('home-lab-safety', 3, 'tf',
 'Suspicious files are safe to open on your daily laptop if you are careful about what you click.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 1,
 'Analysis belongs in isolated, disposable VMs - snapshots discarded afterward - never on a machine holding your real accounts.'),
('how-computers-work', 1, 'mcq',
 'A program runs slowly with high disk activity but low CPU. What is the most likely explanation?',
 '[{"id":"a","text":"The CPU is overheating"},{"id":"b","text":"The GPU driver is missing"},{"id":"c","text":"It is I/O bound - waiting on storage more than on compute"},{"id":"d","text":"RAM is clocked too fast"}]'::jsonb,
 2,
 'Low CPU plus heavy disk activity is the signature of an I/O bottleneck, not a compute one.'),
('how-computers-work', 2, 'scenario',
 'An application crashes and the OS terminates it. Where do you look first for the system record of that crash?',
 '[{"id":"a","text":"BIOS settings"},{"id":"b","text":"The vendor marketing page"},{"id":"c","text":"The router configuration"},{"id":"d","text":"System event logs (Windows Event Viewer, journald or syslog)"}]'::jsonb,
 3,
 'The OS records process crashes and errors in its event logs - always the first authoritative source.'),
('how-computers-work', 3, 'tf',
 'RAM keeps its contents after power loss, which is why memory forensics can recover data from a machine days later.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 1,
 'RAM is volatile - it loses contents within moments of power loss. That is why live memory capture must happen while the machine runs.'),
('files-filesystems', 1, 'mcq',
 'On a traditional spinning disk, what is the difference between deleting a file and secure deletion?',
 '[{"id":"a","text":"They are identical operations"},{"id":"b","text":"Normal deletion unlinks the file but leaves data blocks recoverable until overwritten; secure deletion overwrites them"},{"id":"c","text":"Normal deletion zeroes every block instantly"},{"id":"d","text":"Deletion copies the file to the cloud first"}]'::jsonb,
 1,
 'unlink removes the pointer, not the data. Until blocks are overwritten, forensic recovery is possible.'),
('files-filesystems', 2, 'scenario',
 'On Linux, a file has mode 640, owner alice, group devs. Bob is a member of devs. What can Bob do?',
 '[{"id":"a","text":"Read the file but not modify it"},{"id":"b","text":"Read and write the file"},{"id":"c","text":"Nothing - group rights do not apply to members"},{"id":"d","text":"Change the file owner"}]'::jsonb,
 0,
 '640 = owner rw, group r, others none. Bob gets read-only via the group entry.'),
('files-filesystems', 3, 'scenario',
 'A forensic investigator images a disk and analyzes only the image. Why?',
 '[{"id":"a","text":"Images are smaller than the original disk"},{"id":"b","text":"The original disk is always encrypted"},{"id":"c","text":"It looks better in the report"},{"id":"d","text":"To keep original evidence pristine while analysis tools modify whatever they examine"}]'::jsonb,
 3,
 'Analysis tools change what they touch (mounting updates timestamps). Working on the image preserves the original evidence.'),
('virtualization', 1, 'mcq',
 'What does a hypervisor do?',
 '[{"id":"a","text":"Creates and runs virtual machines, mediating their access to CPU, memory and devices while keeping them isolated"},{"id":"b","text":"Routes packets between VLANs"},{"id":"c","text":"Manages browser extensions"},{"id":"d","text":"Signs TLS certificates"}]'::jsonb,
 0,
 'The hypervisor is the layer that virtualizes hardware and enforces isolation between guests.'),
('virtualization', 2, 'scenario',
 'Your lab VM reaches the internet through NAT provided by the hypervisor. A key security property of that default is',
 '[{"id":"a","text":"The VM receives its own public IP address"},{"id":"b","text":"External machines cannot initiate connections to the VM, limiting exposure"},{"id":"c","text":"NAT encrypts all VM traffic end to end"},{"id":"d","text":"The VM shares malware with the host"}]'::jsonb,
 1,
 'NAT allows outbound connections but blocks unsolicited inbound ones - a useful containment default for lab VMs.'),
('virtualization', 3, 'tf',
 'A snapshot captures the state of a VM disk (and often memory) at a point in time so you can return to it later.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'That is exactly what a snapshot is - a restorable point-in-time state.'),
('troubleshooting-basics', 1, 'scenario',
 'A web app fails for one user but works for everyone else. Best first step?',
 '[{"id":"a","text":"Reproduce with that user context and narrow the layer: their machine, their network, their account, or the app itself"},{"id":"b","text":"Rebuild the server"},{"id":"c","text":"Restart every service"},{"id":"d","text":"Reinstall the user operating system"}]'::jsonb,
 0,
 'Reproduce first, then bisect the layers. Fixing what you have not reproduced is guesswork.'),
('troubleshooting-basics', 2, 'mcq',
 'You changed a config and broke a service. What is the fastest safe path back?',
 '[{"id":"a","text":"Change more settings until something works"},{"id":"b","text":"Wait a day for caches to expire"},{"id":"c","text":"Roll back the change, confirm recovery, then re-apply step by step while watching logs"},{"id":"d","text":"Reboot repeatedly"}]'::jsonb,
 2,
 'Restore working state first, then reintroduce changes incrementally so you know exactly which step breaks.'),
('troubleshooting-basics', 3, 'tf',
 'Good troubleshooting starts with a testable hypothesis rather than random fixes.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'Form a hypothesis, design a check, observe. Random fix-throwing wastes time and can add new breakage.'),
('networking-models', 1, 'scenario',
 'A support ticket says: the app cannot reach the database server, but pinging it works. Which layer is most likely fine?',
 '[{"id":"a","text":"Layer 1/2 connectivity is fine - the problem is likely a higher layer, like a closed port or application config"},{"id":"b","text":"The physical cable must be unplugged"},{"id":"c","text":"DNS must be broken"},{"id":"d","text":"The database is always at fault"}]'::jsonb,
 0,
 'A successful ping proves the path and link work. The failure lives above: firewall, service, or application config.'),
('networking-models', 2, 'mcq',
 'Which statement about the TCP/IP and OSI models is correct?',
 '[{"id":"a","text":"TCP/IP has 7 layers; OSI has 4"},{"id":"b","text":"OSI is a 7-layer conceptual model; TCP/IP is the 4-to-5-layer model the internet actually runs"},{"id":"c","text":"They are incompatible and cannot be compared"},{"id":"d","text":"OSI replaced TCP/IP in production networks"}]'::jsonb,
 1,
 'OSI is the teaching and troubleshooting vocabulary (7 layers); TCP/IP is the working model real networks implement.'),
('networking-models', 3, 'tf',
 'Encapsulation means each layer adds its own header to the data it receives from the layer above.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'Application data gets a TCP header, then an IP header, then a frame header - each layer wrapping the last.'),
('ip-addressing', 1, 'scenario',
 'Your laptop shows 192.168.1.50/24 and the gateway is 192.168.1.1. Which destination requires the gateway?',
 '[{"id":"a","text":"192.168.1.25"},{"id":"b","text":"The printer at 192.168.1.200"},{"id":"c","text":"93.184.216.34 - a public web server"},{"id":"d","text":"127.0.0.1"}]'::jsonb,
 2,
 'Same /24 subnet = direct delivery. Anything outside 192.168.1.0/24 (like a public IP) goes to the gateway. Loopback never leaves the host.'),
('ip-addressing', 2, 'mcq',
 'What does the subnet mask in CIDR /26 tell you?',
 '[{"id":"a","text":"The network has 26 routers"},{"id":"b","text":"26 bits are for the network portion, leaving 6 host bits - 62 usable hosts"},{"id":"c","text":"The first octet is the network"},{"id":"d","text":"There are 26 available addresses"}]'::jsonb,
 1,
 '/26 = 26 network bits, 6 host bits: 64 addresses, 62 usable after network and broadcast.'),
('ip-addressing', 3, 'tf',
 'RFC 1918 addresses like 10.0.0.0/8 and 192.168.0.0/16 are routable on the public internet.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 1,
 'Private ranges are not routable on the public internet - they work only inside networks, usually paired with NAT.'),
('tcp-udp-ports', 1, 'scenario',
 'A video call tolerates a dropped frame but cannot survive delayed packets. Which transport fits and why?',
 '[{"id":"a","text":"UDP - no retransmit delays; lost packets are simply gone, which the app tolerates"},{"id":"b","text":"TCP - it must retransmit everything"},{"id":"c","text":"ICMP - it is fastest"},{"id":"d","text":"ARP - it is link layer"}]'::jsonb,
 0,
 'Live media prefers UDP: fresher beats complete. TCP retransmission would arrive too late to matter.'),
('tcp-udp-ports', 2, 'mcq',
 'A client reaches a web server on port 443. What is the best description of the sockets involved?',
 '[{"id":"a","text":"Both sides use source and destination port 443"},{"id":"b","text":"One connection: client IP + ephemeral port, server IP + port 443"},{"id":"c","text":"Sockets exist only on servers"},{"id":"d","text":"Port 443 identifies the client machine"}]'::jsonb,
 1,
 'A socket is an (IP, port) pair. The client gets a random high source port; the server listens on 443.'),
('tcp-udp-ports', 3, 'tf',
 'Receiving traffic on an unexpected high port is itself proof the service is malicious.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 1,
 'High ports are normal for ephemeral client connections, P2P, and custom services. Suspicion needs context, not a port number alone.'),
('dns-fundamentals', 1, 'scenario',
 'Every website fails by name but 93.184.216.34 loads directly. What does that immediately suggest?',
 '[{"id":"a","text":"The internet connection is down"},{"id":"b","text":"DNS resolution is failing - names are not translating to addresses"},{"id":"c","text":"The browser cache is full"},{"id":"d","text":"The TLS certificates expired"}]'::jsonb,
 1,
 'IP works, name does not: the failure sits in name resolution, not connectivity.'),
('dns-fundamentals', 2, 'mcq',
 'What is the practical difference between recursive and iterative DNS queries?',
 '[{"id":"a","text":"Recursive resolvers chase the full answer on behalf of the client; iterative queries return whatever referral the server has"},{"id":"b","text":"Recursive is slower and never cached"},{"id":"c","text":"They are two names for one behavior"},{"id":"d","text":"Iterative queries only work over HTTPS"}]'::jsonb,
 0,
 'Your resolver does the legwork recursively (asking root, TLD, authoritative); a server answering iteratively just hands back its best referral.'),
('dns-fundamentals', 3, 'tf',
 'DNS over HTTPS (DoH) encrypts DNS lookups so local network observers cannot read which names you resolve.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'DoH wraps DNS in TLS, hiding queries from on-path observers - though the DoH provider itself still sees them.'),
('dhcp-arp', 1, 'scenario',
 'A device boots on a network it has never seen and gets an IP with no manual setup. Which protocol made that happen?',
 '[{"id":"a","text":"ARP"},{"id":"b","text":"DHCP"},{"id":"c","text":"DNS"},{"id":"d","text":"NAT"}]'::jsonb,
 1,
 'DHCP leases an address plus gateway and DNS config automatically. ARP comes later, resolving that IP to a MAC.'),
('dhcp-arp', 2, 'mcq',
 'What does ARP do on a local network?',
 '[{"id":"a","text":"Assigns IP addresses to new hosts"},{"id":"b","text":"Translates domain names to IPs"},{"id":"c","text":"Finds the MAC address that belongs to a known IP on the same link"},{"id":"d","text":"Routes packets between subnets"}]'::jsonb,
 2,
 'ARP asks the LAN: who has this IP? The owner replies with its MAC so frames can be addressed.'),
('dhcp-arp', 3, 'tf',
 'A rogue DHCP server on a LAN can hand out a malicious gateway address and intercept traffic.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'That is exactly how DHCP spoofing attacks work - clients trust whatever DHCP tells them unless the network protects them (e.g. DHCP snooping).'),
('http-https-tls', 1, 'scenario',
 'You connect to a site and the browser shows a padlock. What does that padlock actually prove?',
 '[{"id":"a","text":"The site is safe and honest"},{"id":"b","text":"Traffic is encrypted and the certificate was issued for that domain by a CA the browser trusts - nothing about content safety"},{"id":"c","text":"No malware is on the server"},{"id":"d","text":"The site cannot track you"}]'::jsonb,
 1,
 'TLS proves confidentiality and server identity, not trustworthiness. Plenty of phishing sites have valid certificates.'),
('http-https-tls', 2, 'mcq',
 'Which HTTP status code class means the request succeeded, and which signals the client must take another step (like following a redirect)?',
 '[{"id":"a","text":"2xx succeeds; 3xx redirects"},{"id":"b","text":"2xx succeeds; 4xx redirects"},{"id":"c","text":"1xx succeeds; 5xx redirects"},{"id":"d","text":"3xx succeeds; 4xx redirects"}]'::jsonb,
 0,
 '2xx = success, 3xx = redirection, 4xx = client error, 5xx = server error.'),
('http-https-tls', 3, 'tf',
 'Cookies marked Secure and HttpOnly still travel over plain HTTP if the user types the http:// address.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 1,
 'The Secure attribute tells the browser to only send the cookie over HTTPS - exactly the protection this scenario describes.'),
('packet-analysis', 1, 'scenario',
 'Wireshark shows many TCP retransmissions on one flow while other flows run clean. What does that localize?',
 '[{"id":"a","text":"The whole network is down"},{"id":"b","text":"The capture filter is wrong"},{"id":"c","text":"A problem on that specific path or endpoint - packet loss or congestion on that flow, not the network at large"},{"id":"d","text":"DNS is failing for everyone"}]'::jsonb,
 2,
 'Retransmissions mean sent segments were never acknowledged. When only one flow suffers, the issue is that path or endpoint, not the whole network.'),
('packet-analysis', 2, 'mcq',
 'What is the practical purpose of a capture filter (BPF) like "host 10.0.0.5" in tcpdump?',
 '[{"id":"a","text":"It encrypts the captured packets"},{"id":"b","text":"It limits what the kernel captures, reducing noise and file size before analysis even starts"},{"id":"c","text":"It decodes TLS traffic"},{"id":"d","text":"It scans the target host for vulnerabilities"}]'::jsonb,
 1,
 'Capture filters run early in the capture path - fewer packets collected, cleaner analysis. Display filters in Wireshark narrow what you look at.'),
('packet-analysis', 3, 'tf',
 'Following a TCP stream in Wireshark reassembles the bidirectional conversation so you can read the application payload in order.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'Stream reassembly sorts segments into a readable conversation - the core technique for analyzing HTTP, SMTP, and similar protocols.'),
('network-devices', 1, 'scenario',
 'Home devices with private IPs (192.168.x.x) all share one public IP to reach the internet. Which device function enables that?',
 '[{"id":"a","text":"The switch bridging the LAN"},{"id":"b","text":"The DNS resolver"},{"id":"c","text":"NAT on the router, rewriting private source addresses to the shared public address"},{"id":"d","text":"The DHCP lease timer"}]'::jsonb,
 2,
 'NAT is the many-to-one translation that lets a LAN share one public address.'),
('network-devices', 2, 'mcq',
 'What is the key difference between a stateful firewall and a simple packet filter?',
 '[{"id":"a","text":"Stateful firewalls track connection state and allow reply traffic of established flows; packet filters judge each packet in isolation"},{"id":"b","text":"Packet filters are always faster and safer"},{"id":"c","text":"Stateful firewalls cannot inspect TCP"},{"id":"d","text":"There is no practical difference"}]'::jsonb,
 0,
 'State tracking is the feature: replies to an outbound request come back automatically, unsolicited inbound does not.'),
('network-devices', 3, 'tf',
 'A VPN creates an encrypted tunnel so traffic crossing an untrusted network is protected from interception and tampering.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'Confidentiality and integrity on untrusted links is exactly the job of a VPN tunnel.'),
('linux-fundamentals', 1, 'scenario',
 'A command fails with Permission denied but you own the file. What is the most likely cause and fix?',
 '[{"id":"a","text":"The execute bit is missing - chmod +x adds it"},{"id":"b","text":"The disk is full"},{"id":"c","text":"The file must be moved to /tmp"},{"id":"d","text":"You need to reboot"}]'::jsonb,
 0,
 'Ownership is not enough: the mode bits decide what the owner may do. Missing execute permission is the classic cause.'),
('linux-fundamentals', 2, 'mcq',
 'In Linux, what does the everything-is-a-file model mean for you as an administrator?',
 '[{"id":"a","text":"Devices, sockets, and process info appear in the filesystem and can be read with the same tools"},{"id":"b","text":"All files must be owned by root"},{"id":"c","text":"Linux has no access control"},{"id":"d","text":"Only text files are allowed"}]'::jsonb,
 0,
 'Devices, sockets, and process info all appear in the filesystem and can be read with the same tools.'),
('linux-fundamentals', 3, 'tf',
 'The sudo command lets an authorized user run a command with another identity (typically root), with the action logged.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'sudo is per-command privilege elevation with an audit trail - far better than logging in as root.'),
('linux-permissions', 1, 'scenario',
 'A web server can read /srv/site/index.html but gets Permission denied on /srv/site. What is the most likely cause?',
 '[{"id":"a","text":"The directory is missing an execute bit, which is required to traverse it"},{"id":"b","text":"index.html has the immutable flag"},{"id":"c","text":"The web server needs a restart"},{"id":"d","text":"SELinux never blocks directories"}]'::jsonb,
 0,
 'On directories, x means traverse. Without it, files inside are unreachable no matter their own modes.'),
('linux-permissions', 2, 'mcq',
 'What does the setuid bit on an executable do?',
 '[{"id":"a","text":"Runs the program with the effective identity of the file owner rather than the caller"},{"id":"b","text":"Prevents the file from being deleted"},{"id":"c","text":"Makes the file executable by root only"},{"id":"d","text":"Compresses the binary"}]'::jsonb,
 0,
 'setuid is how passwd can write /etc/shadow as root - and why setuid binaries are a privilege-escalation target.'),
('linux-permissions', 3, 'scenario',
 'Which command grants group write on project/ and nothing to others?',
 '[{"id":"a","text":"chmod 770 project/"},{"id":"b","text":"chmod 777 project/"},{"id":"c","text":"chmod o+r project/"},{"id":"d","text":"chown root project/"}]'::jsonb,
 0,
 '7 = owner rwx, 7 = group rwx, 0 = others none. 777 hands it to the world; o+r only adds read.'),
('linux-services-logs', 1, 'scenario',
 'A service is down after a reboot. What is the first diagnostic command most Linux admins run?',
 '[{"id":"a","text":"systemctl status <service> - state, recent log lines, and enablement in one view"},{"id":"b","text":"Reinstall the package"},{"id":"c","text":"Reboot again and hope"},{"id":"d","text":"Check the CPU temperature"}]'::jsonb,
 0,
 'systemctl status shows active or inactive, why it died, and the last journal entries - the fastest start.'),
('linux-services-logs', 2, 'mcq',
 'Where does journald keep its logs, and how do you read them?',
 '[{"id":"a","text":"Binary journal files under /var/log, read with journalctl"},{"id":"b","text":"In the Windows registry"},{"id":"c","text":"Only in encrypted cloud storage"},{"id":"d","text":"In /etc/passwd"}]'::jsonb,
 0,
 'journald stores structured binary journals; journalctl queries them by unit, time, priority, and more.'),
('linux-services-logs', 3, 'tf',
 'SSH key authentication is generally preferred over passwords because keys resist brute force far better and enable agent-based workflows.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'Long random keys cannot be guessed the way passwords can, and disabling password auth removes that attack surface.'),
('windows-fundamentals', 1, 'scenario',
 'An application keeps crashing on a Windows machine. Which built-in tool gives you the richest first look at what happened?',
 '[{"id":"a","text":"Event Viewer - application and system logs record crashes, errors, and sources"},{"id":"b","text":"Disk Cleanup"},{"id":"c","text":"The desktop wallpaper properties"},{"id":"d","text":"Device Manager only"}]'::jsonb,
 0,
 'Event Viewer is the Windows system record: application crashes, service failures, and error codes live there.'),
('windows-fundamentals', 2, 'mcq',
 'What is the Windows registry, practically speaking?',
 '[{"id":"a","text":"A hierarchical database of configuration for the OS and applications"},{"id":"b","text":"A list of installed antivirus products"},{"id":"c","text":"The Recycle Bin index"},{"id":"d","text":"A log of every keyboard press"}]'::jsonb,
 0,
 'Hives like HKLM and HKCU hold system and per-user configuration - a core artifact for both admin work and forensics.'),
('windows-fundamentals', 3, 'tf',
 'NTFS permissions and share permissions are separate layers, and the most restrictive effective permission wins when accessing a file over a network share.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'Effective access over a share combines both layers; the tighter one applies.'),
('windows-administration', 1, 'scenario',
 'You must repeatedly create users, set ACLs, and pull event logs on many Windows servers. Which tool is designed for exactly this automation?',
 '[{"id":"a","text":"PowerShell - an object-based shell built for Windows administration at scale"},{"id":"b","text":"Notepad macros"},{"id":"c","text":"Manually clicking through Control Panel on each server"},{"id":"d","text":"The registry editor alone"}]'::jsonb,
 0,
 'PowerShell cmdlets work with objects, not text, and were purpose-built for repeatable Windows administration.'),
('windows-administration', 2, 'mcq',
 'In PowerShell, what does the pipeline pass between commands?',
 '[{"id":"a","text":"Raw strings only"},{"id":"b","text":"Structured objects whose properties the next command can use directly"},{"id":"c","text":"Compressed archives"},{"id":"d","text":"Assembly bytecode"}]'::jsonb,
 1,
 'Object piping is the PowerShell superpower: Get-Process | Where-Object filters on real properties, no text parsing.'),
('windows-administration', 3, 'tf',
 'Windows service accounts should run with least privilege - not as local administrator by default.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'A compromised over-privileged service account becomes a system-wide foothold. Least privilege caps the blast radius.'),
('python-basics', 1, 'scenario',
 'A script must repeat a health-check every 10 seconds until a service responds. Which structure fits best?',
 '[{"id":"a","text":"A while loop with a sleep, exiting when the check succeeds"},{"id":"b","text":"A single if statement"},{"id":"c","text":"A list comprehension"},{"id":"d","text":"Recursive directory walking"}]'::jsonb,
 0,
 'Condition unknown in advance + repeat until success = while loop with a delay between attempts.'),
('python-basics', 2, 'mcq',
 'Why do Python programmers prefer with open(path) as f: over manual open() and close()?',
 '[{"id":"a","text":"It reads files faster"},{"id":"b","text":"The context manager guarantees the file is closed even if an error occurs mid-processing"},{"id":"c","text":"It encrypts the file automatically"},{"id":"d","text":"It only works on Linux"}]'::jsonb,
 1,
 'The with statement ties cleanup to the block, so exceptions cannot leak open handles.'),
('python-basics', 3, 'tf',
 'In Python, a list is mutable while a tuple is immutable.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'Lists can change in place; tuples cannot - which also makes tuples safe as dictionary keys.'),
('python-automation', 1, 'scenario',
 'A script polls an internal JSON API every minute and must survive the API briefly returning 500 errors without crashing. What is the robust pattern?',
 '[{"id":"a","text":"Remove all error handling so failures surface loudly"},{"id":"b","text":"Wrap the request in try/except, log the failure, and retry on the next cycle"},{"id":"c","text":"Stop the script permanently on the first error"},{"id":"d","text":"Parse the HTML error page as JSON"}]'::jsonb,
 1,
 'Expected, transient failures get caught, logged, and retried - that is what operational automation looks like.'),
('python-automation', 2, 'mcq',
 'What does the requests library give you that raw sockets do not?',
 '[{"id":"a","text":"Higher-level HTTP handling: headers, status codes, JSON decoding, sessions"},{"id":"b","text":"Direct kernel access"},{"id":"c","text":"Guaranteed immunity from rate limits"},{"id":"d","text":"It replaces DNS"}]'::jsonb,
 0,
 'Sockets speak raw TCP; requests speaks HTTP for you - sessions, redirects, and encodings included.'),
('python-automation', 3, 'tf',
 'Never hardcode credentials in scripts; use environment variables or a secrets manager instead.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'Hardcoded secrets leak into git history and screenshots. Environment variables or vaults keep them out of the code.'),
('bash-scripting', 1, 'scenario',
 'You need the list of running processes that contain the word sshd, one per line. Which pipeline fits?',
 '[{"id":"a","text":"ps aux | grep sshd"},{"id":"b","text":"ls sshd"},{"id":"c","text":"cat /etc/passwd"},{"id":"d","text":"dd if=/dev/zero"}]'::jsonb,
 0,
 'ps lists processes, grep filters lines - the classic small-tools-composed pattern of the shell.'),
('bash-scripting', 2, 'mcq',
 'What does set -euo pipefail do at the top of a bash script?',
 '[{"id":"a","text":"It makes the script exit on errors and unset variables, and fail a pipeline if any command fails - safer defaults"},{"id":"b","text":"It speeds up the script"},{"id":"c","text":"It enables debugging output only"},{"id":"d","text":"It runs everything as root"}]'::jsonb,
 0,
 'e = exit on error, u = error on unset variables, pipefail = pipeline fails if any stage fails. Fail fast, fail loud.'),
('bash-scripting', 3, 'tf',
 'In bash, command output can be redirected to a file with > and appended with >>.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 '> truncates and writes, >> appends - basic but constantly used redirection.'),
('javascript-basics', 1, 'scenario',
 'A security review flags code that inserts user-supplied text directly into the page with innerHTML. What is the risk and the fix?',
 '[{"id":"a","text":"Slower rendering; use a bigger buffer"},{"id":"b","text":"No risk - browsers sanitize innerHTML"},{"id":"c","text":"XSS: injected markup can execute; use textContent or proper sanitization"},{"id":"d","text":"Memory leak; disable JavaScript"}]'::jsonb,
 2,
 'innerHTML treats input as markup. Untrusted input through it is the classic stored/reflected XSS sink; textContent inserts text safely.'),
('javascript-basics', 2, 'mcq',
 'What does the same-origin policy restrict?',
 '[{"id":"a","text":"How many tabs a browser may open"},{"id":"b","text":"Scripts on one origin reading data from another origin without permission"},{"id":"c","text":"The size of cookies"},{"id":"d","text":"Download speed"}]'::jsonb,
 1,
 'SOP isolates origins from each other so evil.example cannot read your bank session data; CORS grants controlled exceptions.'),
('javascript-basics', 3, 'tf',
 'The fetch API returns a promise that resolves to a Response object, whose json() method also returns a promise.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'Two-stage async is why you await fetch(...) then await response.json() - a common beginner stumble.'),
('c-memory-basics', 1, 'scenario',
 'A C program crashes intermittently after returning from a function that returned a pointer to one of its local variables. What is the most likely cause?',
 '[{"id":"a","text":"The local variable lived on the stack, which is invalid once the function returns - a dangling pointer"},{"id":"b","text":"The compiler is too old"},{"id":"c","text":"The CPU overheated"},{"id":"d","text":"The file descriptor was closed twice"}]'::jsonb,
 0,
 'Stack frames die at return. Pointers to locals are dangling - the data may look intact briefly, then fail unpredictably.'),
('c-memory-basics', 2, 'mcq',
 'What is a buffer overflow, in one sentence?',
 '[{"id":"a","text":"Writing past the end of a fixed-size memory buffer, potentially overwriting adjacent data or control information"},{"id":"b","text":"Allocating too little swap space"},{"id":"c","text":"A disk filling up with log files"},{"id":"d","text":"Any program that runs slowly"}]'::jsonb,
 0,
 'Out-of-bounds writes corrupt neighbors; overwriting a return address turns a bug into code execution.'),
('c-memory-basics', 3, 'tf',
 'Compiler protections like stack canaries, ASLR, and NX/DEP reduce the practical exploitability of memory-safety bugs.',
 '[{"id":"yes","text":"Yes"},{"id":"no","text":"No"}]'::jsonb,
 0,
 'They do not fix the bug, but they raise the cost of exploiting it - which is why they are standard hardening layers.')

on conflict (topic_slug, position) do update set
  kind = excluded.kind,
  question = excluded.question,
  choices = excluded.choices,
  answer_index = excluded.answer_index,
  explanation = excluded.explanation;
