-- ==========================================================================
-- Cyber_Path migration 0016 - project idea catalog
-- Twelve curated ideas across difficulty levels. Every idea maps to slugs
-- from public.skills and carries an explicit authorized-use statement.
-- Idempotent: upsert on slug.
-- ==========================================================================

insert into public.project_ideas
  (slug, title, summary, why_build_it, difficulty, estimated_hours, skills, requirements, milestones, authorized_use, order_index) values

('password-strength-analyzer', 'Password strength analyzer',
 'A CLI or web tool that scores password strength using entropy, common-pattern detection and breach-list checks.',
 'Passwords are the front door of authentication. Building the scorer teaches entropy math, pattern matching and why composition rules alone fail.',
 'beginner', 8,
 '["python", "security-literacy"]',
 '["Score by estimated entropy, not by rule checkboxes", "Detect common patterns: dates, leetspeak, keyboard walks", "Optionally check a local breach-list file (never call paid APIs)", "Never log or transmit entered passwords"]',
 '["Design the scoring model on paper", "Implement entropy calculation with tests", "Add pattern detection", "Write README explaining the threat model", "Publish the repo"]',
 'Runs entirely on passwords you create yourself. Never test it against real accounts.',
 1),

('log-analyzer', 'Log analyzer',
 'Parse Linux or Windows logs and surface failed logins, new users and other anomalies in a readable summary.',
 'Log analysis is the daily bread of blue-team work. Building a parser teaches log formats, baselines and what actually looks abnormal.',
 'beginner', 12,
 '["python", "bash", "linux"]',
 '["Parse auth.log or Windows Security EVTX (via a CSV export is fine)", "Flag failed-login bursts, off-hours activity, new sudo users", "Output both human summary and JSON", "Document every detection rule in plain language"]',
 '["Collect sample logs you generated yourself", "Build the parser with unit tests", "Add three anomaly rules", "Generate a report from a test dataset", "Publish the repo"]',
 'Analyze logs from machines you own or lab VMs you created. Real user data stays out.',
 2),

('file-integrity-monitor', 'File integrity monitor',
 'Watch a directory and report creations, modifications and deletions using cryptographic hashes.',
 'Integrity monitoring is a core detection primitive (the same idea behind tripwire and OSSEC) and teaches hashing in a practical way.',
 'beginner', 10,
 '["python", "linux", "security-literacy"]',
 '["Snapshot a directory as a hash database (SHA-256)", "Detect and report create/modify/delete between runs", "Ignore configured noise (temp files)", "Explain how attackers tamper with baseline files - and how your tool resists it"]',
 '["Design the baseline format", "Implement hashing and diffing with tests", "Add an ignore list", "Simulate tampering in a lab VM and detect it", "Publish the repo"]',
 'Monitor directories you own inside your own machine or lab VMs.',
 3),

('port-scanner-local', 'Local port scanner',
 'A small TCP connect scanner for your own machine or lab network, with service-name lookup and clean output.',
 'You cannot defend sockets you do not understand. Writing a scanner demystifies TCP handshakes, ports and what tools like nmap do under the hood.',
 'beginner', 10,
 '["networking", "python"]',
 '["TCP connect scan with configurable timeout", "Resolve common port numbers to service names", "Scan only hosts you explicitly allow (config allowlist)", "Print results as a table and JSON"]',
 '["Implement the connect scanner with tests against localhost", "Add the host allowlist guard", "Add service-name mapping", "Scan your own lab VM and document findings", "Publish the repo"]',
 'Strictly scan 127.0.0.1 and lab VMs you own. The allowlist exists so scanning other hosts is a deliberate config change, never an accident.',
 4),

('secure-notes-app', 'Secure notes application',
 'A small web app where notes are encrypted client-side before storage, with login and session handling done right.',
 'Building the app you would attack teaches authentication, sessions, crypto choices and where each typically breaks.',
 'beginner', 16,
 '["javascript", "tls", "security-literacy"]',
 '["Encrypt note contents client-side with a key derived from the passphrase (WebCrypto)", "Standard login with rate limiting", "CSRF protection and secure cookie flags", "Threat-model document: what this design protects and what it cannot"]',
 '["Design the data model and crypto approach", "Build CRUD with authentication", "Add client-side encryption", "Security-review your own app and fix findings", "Publish with the threat model in the README"]',
 'Your own app on your own machine. Do not deploy it publicly without a real security review - state that honestly in the README.',
 5),

('phishing-awareness-simulator', 'Phishing awareness trainer',
 'An interactive quiz app that shows real (redacted) phishing examples and teaches the tells: lookalike domains, urgency, mismatched links.',
 'Recognizing phishing is a trainable skill. Building the trainer teaches email headers, domain spoofing and social engineering without touching anyone.',
 'beginner', 12,
 '["javascript", "security-literacy", "legal-ethics"]',
 '["Curate 10+ redacted example emails (yours or public samples)", "Interactive: user guesses phishing or legit, gets explanation", "Score session with per-question explanations", "Content review note: where the examples came from"]',
 '["Collect and sanitize example emails", "Design the question flow", "Build the quiz with scoring", "Write explanations for each tell", "Publish"]',
 'Educational content only - no live sending, no credential capture, ever. Examples are simulated or redacted.',
 6),

('packet-analysis-toolkit', 'Packet analysis mini toolkit',
 'A Python toolkit that reads pcap files and reports top talkers, protocol distribution and suspicious patterns like port-scan signatures.',
 'Reading pcaps programmatically cements packet structure far better than Wireshark alone, and mirrors real SOC triage work.',
 'intermediate', 18,
 '["packet-analysis", "networking", "python"]',
 '["Parse pcap files (scapy is allowed)", "Top talkers, protocol breakdown, port statistics", "Detect simple signatures: SYN scan pattern, DNS exfil attempt shape", "Bundle a lab pcap you generated yourself"]',
 '["Generate your own lab pcaps", "Build the parser and statistics", "Add two detection signatures", "Write a detection-logic README", "Publish"]',
 'Analyze captures you recorded in your own lab. No sniffing networks you do not own or have permission to monitor.',
 7),

('vuln-management-dashboard', 'Vulnerability management dashboard',
 'A web app that ingests scan results (CSV/JSON), deduplicates findings and tracks severity, status and remediation over time.',
 'The vulnerability lifecycle - found, triaged, fixed, verified - is the operational heart of AppSec and IT-security roles.',
 'intermediate', 24,
 '["python", "javascript", "security-literacy"]',
 '["Import scan exports in a documented format", "Deduplicate across scans (same host + service + finding)", "Severity buckets with status workflow (open, triaged, fixed, accepted)", "Dashboard views: trend, oldest unfixed, by-host", "Role-based access: viewer vs manager"]',
 '["Define the import schema", "Build ingestion and dedup", "Add the status workflow", "Build dashboard views", "Security-review the app itself", "Publish with sample data"]',
 'Use synthetic or scan data from your own lab. Never load client scan data into a portfolio project.',
 8),

('siem-style-log-dashboard', 'SIEM-style log dashboard',
 'Ingest logs from your lab VMs, index them, and build a live dashboard with saved searches and alert rules.',
 'A mini-SIEM teaches the pipeline: collection, parsing, indexing, detection, alerting - the vocabulary of every SOC job posting.',
 'intermediate', 30,
 '["linux", "python", "packet-analysis", "security-literacy"]',
 '["Collect logs from 2+ lab VMs (syslog or file shipping)", "Parse into structured events with consistent fields", "Store and query (SQLite/Postgres or a search engine)", "Three working alert rules with a notification", "Document the pipeline architecture"]',
 '["Stand up lab VMs generating logs", "Build collection and parsing", "Add storage and search", "Implement alert rules", "Build the dashboard UI", "Write the architecture doc and publish"]',
 'All telemetry comes from VMs you own. Keep the dashboard bound to localhost or your lab network.',
 9),

('secure-api', 'Secure API with auth and rate limiting',
 'A REST API implementing the full security checklist: auth tokens, per-client rate limits, input validation, and honest error messages.',
 'APIs are the attack surface of everything modern. Building one correctly - then testing it - converts OWASP theory into muscle memory.',
 'intermediate', 24,
 '["python", "javascript", "tls", "security-literacy"]',
 '["Token-based auth with expiry and revocation", "Per-client rate limiting (429 with Retry-After)", "Strict input validation on every endpoint", "Uniform, non-revealing error responses", "Write and run an attack checklist against your own API (auth bypass, injection, IDOR attempts)"]',
 '["Design endpoints and auth model", "Implement with validation on every input", "Add rate limiting", "Attack-test your own API and document results", "Publish with the security checklist in the README"]',
 'Test only the API you built, running locally or in your lab. The README must say so explicitly.',
 10),

('honeypot-controlled', 'Lab honeypot',
 'A low-interaction honeypot (fake SSH banner, fake services) deployed in an isolated lab network, logging every probe it receives.',
 'A honeypot shows you what real internet background noise looks like - and teaches you to instrument, alert and analyze attacker behavior safely.',
 'advanced', 30,
 '["networking", "linux", "packet-analysis", "bash"]',
 '["Fake service(s) that log connection attempts, banners grabbed, commands typed", "Isolated network segment that cannot reach your real LAN", "Alert on first contact (email or dashboard)", "Analysis writeup: what showed up and when", "Kill-switch documentation: how to turn it off in one command"]',
 '["Design isolation (host-only network, no bridge)", "Implement logging fake services", "Add the alerting", "Run for 1-2 weeks and collect data", "Write the analysis report and publish"]',
 'Deploy ONLY in an isolated lab network (host-only/internal). Never on a machine or network with real services or data. Document the isolation design as part of the project.',
 11),

('detection-pipeline', 'Threat detection pipeline',
 'An end-to-end prototype: events flow in from lab VMs, enrichment and detection rules run, alerts land in a queue with an analyst-facing case view.',
 'This is the capstone: collection, detection, enrichment, triage and documentation in one system - the closest a home lab gets to real detection engineering.',
 'advanced', 40,
 '["python", "linux", "packet-analysis", "security-literacy"]',
 '["Event ingestion from multiple lab sources", "Rule engine: at least five detections across auth, network and process events", "Enrichment stage (geolocation or known-bad list, locally cached)", "Case queue with statuses and analyst notes", "Detection rules documented with rationale and false-positive notes"]',
 '["Design the event schema end to end", "Build ingestion from 2+ sources", "Implement the rule engine with tests", "Add enrichment and the case queue", "Tune rules on real lab noise, document FP rates", "Publish with the architecture writeup"]',
 'All data sources are VMs you own in an isolated lab. Enrichment uses local caches, not live third-party APIs with your data.',  12)

on conflict (slug) do update set
  title = excluded.title,
  summary = excluded.summary,
  why_build_it = excluded.why_build_it,
  difficulty = excluded.difficulty,
  estimated_hours = excluded.estimated_hours,
  skills = excluded.skills,
  requirements = excluded.requirements,
  milestones = excluded.milestones,
  authorized_use = excluded.authorized_use,
  order_index = excluded.order_index;
