-- ===========================================================================
-- Cyber_Path migration 0024 — labs seed (categories + starter catalog)
--
-- Seeds the lab catalog with well-known, free, reputable external labs,
-- CTFs and home-lab exercises. Every URL is a real public resource; no
-- unofficial API dependencies. Where a lab is exactly the exercise a
-- topic's seeded Practice hint describes, ticks_practice_stage is true —
-- otherwise false. Built-in simulations arrive in later migrations.
--
-- Idempotent: on conflict do update, same style as 0004/0016.
-- ===========================================================================

-- ── Categories ────────────────────────────────────────────────────────────
insert into public.lab_categories (slug, name, description, order_index) values
  ('linux', 'Linux', 'Command line, permissions, users, services and logs', 10),
  ('windows', 'Windows', 'Registry, NTFS, event logs and PowerShell', 20),
  ('networking', 'Networking', 'Addressing, ports, DNS, HTTP and packet analysis', 30),
  ('web-security', 'Web Security', 'HTTP anatomy, cookies, sessions and injection concepts', 40),
  ('soc-blue-team', 'SOC / Blue Team', 'Log triage, brute-force detection and incident investigation', 50),
  ('digital-forensics', 'Digital Forensics', 'Timelines, log evidence and metadata analysis', 60),
  ('ctf', 'CTF', 'Capture-the-flag events and beginner wargames', 70),
  ('home-lab', 'Home Lab', 'Exercises on systems you own inside an isolated environment', 80)
on conflict (slug) do update
  set name = excluded.name, description = excluded.description, order_index = excluded.order_index;

-- ── Catalog: starter external labs, CTFs and home-lab exercises ───────────
insert into public.labs
  (slug, title, summary, objective, category_slug, lab_type, difficulty,
   estimated_minutes, provider, external_url, instructions, learning_objectives,
   completion_criteria, hints, ticks_practice_stage, is_published)
values
  ('otw-bandit-0-10',
   'OverTheWire Bandit — levels 0–10',
   'Classic SSH wargame: log into a remote box and hunt the password for the next level using pure Linux commands.',
   'Reach Bandit level 10 by reading files, finding hidden files and decoding content across SSH sessions.',
   'linux', 'external', 'beginner', 180,
   'OverTheWire', 'https://overthewire.org/wargames/bandit/',
   'SSH to bandit.labs.overthewire.org port 2220 as bandit0, then solve each level in order. Keep notes on every command that worked — you will reuse them constantly. Authorized: the game is designed for this.',
   array['Navigate a Linux filesystem fluently', 'Find and read hidden and unusual files', 'Use pipes and search tools to locate credentials'],
   '{"mode": "manual"}'::jsonb,
   '[{"tier": 1, "text": "ls -la shows hidden files; most early levels are about reading the right file."}, {"tier": 2, "text": "find / -user bandit7 -size 33c 2>/dev/null style searches solve the middle levels."}]'::jsonb,
   true,
   true),
  ('thm-linux-fundamentals-1',
   'TryHackMe — Linux Fundamentals Part 1',
   'Guided introductory room covering the shell, basic commands and interacting with a Linux machine.',
   'Complete the Linux Fundamentals Part 1 room and run every task''s commands yourself in the attached VM.',
   'linux', 'external', 'beginner', 60,
   'TryHackMe', 'https://tryhackme.com/room/linuxfundamentalspart1',
   'Join the free room, deploy the attached machine and complete each task. Type the commands yourself instead of pasting — muscle memory is the point. Authorized: TryHackMe rooms are built for practice.',
   array['Explain what a shell is and why it matters', 'Run core commands: ls, cd, cat, pwd, echo'],
   '{"mode": "manual"}'::jsonb,
   '[{"tier": 1, "text": "Deploy the AttackBox or OpenVPN before starting; the tasks assume a connected machine."}]'::jsonb,
   true,
   true),
  ('thm-windows-fundamentals-1',
   'TryHackMe — Windows Fundamentals 1',
   'Guided tour of Windows: OS structure, the filesystem, users and basic administration from a security angle.',
   'Complete Windows Fundamentals 1 and locate the registry, event logs and user accounts in the attached VM.',
   'windows', 'external', 'beginner', 60,
   'TryHackMe', 'https://tryhackme.com/room/windowsfundamentals1xbx',
   'Complete each task in the room with the attached Windows VM. On your own machine afterwards, find the equivalents (registry editor, Event Viewer) so the knowledge transfers.',
   array['Navigate the Windows filesystem and registry', 'Locate Windows event logs', 'Describe how Windows separates user privileges'],
   '{"mode": "manual"}'::jsonb,
   '[{"tier": 1, "text": "The room''s VM exists for the whole session — revert it if a task breaks the environment."}]'::jsonb,
   true,
   true),
  ('journalctl-service-triage',
   'Trace a failing service with journalctl',
   'Home-lab exercise: break a systemd service on a VM you own, then recover the root cause purely from journal evidence.',
   'Diagnose a deliberately broken service using systemctl status and journalctl, then document the fix path.',
   'linux', 'home_lab', 'easy', 45,
   '', null,
   'Inside your isolated VM, pick a harmless service (e.g. sshd or a custom unit), break it — wrong config value, bad ListenAddress — then restore it using only journalctl and systemctl output. Matches the roadmap practice exercise for Linux services and logs.',
   array['Read systemctl status output like an investigator', 'Filter journalctl by unit, time and priority', 'Separate symptom from root cause in logs'],
   '{"mode": "manual"}'::jsonb,
   '[{"tier": 1, "text": "journalctl -u <unit> -p err --since today hides the noise."}, {"tier": 2, "text": "The journal shows the exact config line that failed to parse — read it before guessing."}]'::jsonb,
   true,
   true),
  ('nmap-localhost-inventory',
   'Port inventory of your own machine with nmap',
   'Home-lab exercise: scan your own VM, map every listening port to its process, and explain why each one is listening.',
   'Produce a port → process → purpose table for one of your own VMs and justify every entry.',
   'networking', 'home_lab', 'easy', 40,
   '', null,
   'Run nmap against localhost and one other VM interface inside your isolated lab network. For each open port, identify the owning process and whether it should be listening. Finish by closing one unnecessary service.',
   array['Scan safely inside an isolated network you own', 'Map ports to processes and services', 'Judge whether a listening service is expected'],
   '{"mode": "manual"}'::jsonb,
   '[{"tier": 1, "text": "nmap -sV -p- localhost gives service versions; ss -tulpn names the owning processes."}]'::jsonb,
   false,
   true),
  ('dns-capture-analysis',
   'Capture and dissect your own DNS traffic',
   'Home-lab exercise: capture DNS queries with Wireshark while browsing, then read the full query/response exchange.',
   'Explain one DNS lookup end-to-end from your own capture: recursive steps, response codes and records returned.',
   'networking', 'home_lab', 'easy', 50,
   'Wireshark', 'https://www.wireshark.org/docs/',
   'Start a capture with the display filter dns in your VM, visit three new websites, stop the capture. Pick one lookup and trace it: question, response, TTLs, CNAME chains. Do one deliberate NXDOMAIN lookup and note the difference.',
   array['Capture packets on an interface you own', 'Read DNS query and response structure', 'Distinguish NXDOMAIN, NOERROR and truncated responses'],
   '{"mode": "manual"}'::jsonb,
   '[{"tier": 1, "text": "Filter dns.flags.rcode != 0 to find error responses quickly."}]'::jsonb,
   false,
   true),
  ('authlog-bruteforce-triage',
   'Brute-force triage on a sample auth log',
   'SOC-style exercise: generate or obtain an auth log containing brute-force noise, then investigate it like an analyst.',
   'Identify attacker source IPs, targeted accounts, success after failures and a verdict with evidence from the log.',
   'soc-blue-team', 'home_lab', 'intermediate', 60,
   '', null,
   'In your lab VM, run a short scripted burst of failed SSH attempts (against a VM you own) plus one real login. Then triage the log cold: failed counts per source, targeted users, whether any failure burst ended in success. Write a 5-line analyst note with your verdict and IOCs.',
   array['Detect failed-authentication patterns in logs', 'Extract IOCs: source IPs, accounts, timestamps', 'Write a concise, evidence-based analyst verdict'],
   '{"mode": "manual"}'::jsonb,
   '[{"tier": 1, "text": "grep ''Failed password'' auth.log | cut -d'' '' -f10- | sort | uniq -c | sort -rn gives the per-source picture fast."}, {"tier": 2, "text": "Check what happened AFTER the failures, not just the failures — brute force matters when it stops."}]'::jsonb,
   false,
   true),
  ('timeline-metadata-forensics',
   'Reconstruct a timeline from file metadata',
   'Forensics exercise: using files you stage yourself, build an incident timeline from timestamps and metadata only.',
   'Order at least six staged events correctly using file timestamps and metadata, and note which tools lied about what.',
   'digital-forensics', 'home_lab', 'intermediate', 55,
   '', null,
   'Stage a scenario in your VM: create, copy, modify and delete a small set of files over fifteen minutes (touch, cp, mv, echo). Afterwards, reconstruct what happened and in what order using stat, ls timestamps and journal entries. Document where tools disagreed.',
   array['Read file timestamps (mac, change, modify) and their differences', 'Detect timestamp artefacts from copy/move operations', 'Build a defensible event timeline'],
   '{"mode": "manual"}'::jsonb,
   '[{"tier": 1, "text": "stat shows atime/mtime/ctime separately — explain why they differ after a copy."}]'::jsonb,
   false,
   true),
  ('picoctf-first-flags',
   'picoCTF — your first five flags',
   'Beginner CTF platform: solve five easiest challenges and write down the technique each one taught.',
   'Capture five picoCTF flags and log the technique class for each (encoding, web basics, forensics, crypto, misc).',
   'ctf', 'ctf', 'beginner', 120,
   'picoCTF', 'https://picoctf.org/',
   'Register free at picoctf.org, filter challenges to the easiest, and solve any five. For each, record: category, what the challenge showed, the insight that cracked it. Authorized: the platform is designed for this.',
   array['Approach unknown challenges methodically', 'Recognize common encoding and artifact patterns', 'Write brief solution notes you can revisit'],
   '{"mode": "manual"}'::jsonb,
   '[{"tier": 1, "text": "Start with the Forensics and Cryptography easy tiers — they teach reusable basics fastest."}]'::jsonb,
   false,
   true),
  ('portswigger-http-intro',
   'PortSwigger Academy — first HTTP labs',
   'Foundational Web Security Academy labs on HTTP requests, responses and how the proxy sees traffic.',
   'Complete the introductory HTTP labs and explain request structure, headers and cookies from memory.',
   'web-security', 'external', 'easy', 75,
   'PortSwigger Web Security Academy', 'https://portswigger.net/web-security',
   'Work through the Getting Started / HTTP basics labs with Burp''s proxy visible. For each lab, name the vulnerability or concept before submitting — the label matters more than the flag. Authorized: the academy exists for practice.',
   array['Read raw HTTP requests and responses', 'Explain cookies and session tokens at a basic level', 'Use an intercepting proxy deliberately'],
   '{"mode": "manual"}'::jsonb,
   '[{"tier": 1, "text": "Foil the proxy option in Burp helps when labs stall on TLS issues."}]'::jsonb,
   false,
   true)
on conflict (slug) do update
  set title = excluded.title, summary = excluded.summary, objective = excluded.objective,
      category_slug = excluded.category_slug, lab_type = excluded.lab_type,
      difficulty = excluded.difficulty, estimated_minutes = excluded.estimated_minutes,
      provider = excluded.provider, external_url = excluded.external_url,
      instructions = excluded.instructions, learning_objectives = excluded.learning_objectives,
      completion_criteria = excluded.completion_criteria, hints = excluded.hints,
      ticks_practice_stage = excluded.ticks_practice_stage, is_published = excluded.is_published,
      updated_at = now();

-- ── Lab ↔ topic mapping (real roadmap slugs from 0004) ────────────────────
insert into public.lab_topics (lab_slug, topic_slug) values
  ('otw-bandit-0-10', 'linux-fundamentals'),
  ('otw-bandit-0-10', 'files-filesystems'),
  ('thm-linux-fundamentals-1', 'linux-fundamentals'),
  ('thm-windows-fundamentals-1', 'windows-fundamentals'),
  ('journalctl-service-triage', 'linux-services-logs'),
  ('nmap-localhost-inventory', 'tcp-udp-ports'),
  ('dns-capture-analysis', 'dns-fundamentals'),
  ('dns-capture-analysis', 'packet-analysis'),
  ('authlog-bruteforce-triage', 'linux-services-logs'),
  ('timeline-metadata-forensics', 'files-filesystems'),
  ('portswigger-http-intro', 'http-https-tls')
on conflict (lab_slug, topic_slug) do nothing;

-- ── Lab ↔ skill mapping (real skill slugs from 0004) ──────────────────────
insert into public.lab_skills (lab_slug, skill_slug, weight) values
  ('otw-bandit-0-10', 'linux', 2.0),
  ('otw-bandit-0-10', 'shell', 2.0),
  ('thm-linux-fundamentals-1', 'linux', 1.5),
  ('thm-linux-fundamentals-1', 'shell', 1.5),
  ('thm-windows-fundamentals-1', 'windows', 2.0),
  ('journalctl-service-triage', 'linux', 2.0),
  ('journalctl-service-triage', 'shell', 1.0),
  ('nmap-localhost-inventory', 'networking', 2.0),
  ('dns-capture-analysis', 'networking', 1.5),
  ('dns-capture-analysis', 'packet-analysis', 2.5),
  ('authlog-bruteforce-triage', 'linux', 1.0),
  ('authlog-bruteforce-triage', 'packet-analysis', 1.5),
  ('timeline-metadata-forensics', 'compute-concepts', 1.5),
  ('portswigger-http-intro', 'networking', 1.5),
  ('portswigger-http-intro', 'tls', 1.0)
on conflict (lab_slug, skill_slug) do update
  set weight = excluded.weight;
